version: "3.8"
services:
  installer:
    build:
      context: .
      dockerfile: Dockerfile.installer
    volumes:
      - .:/app

  backend:
    build: ./backend
    volumes:
      - ./backend:/app
      - /app/node_modules
    ports:
      - "9428:9428"
    restart: unless-stopped
    depends_on:
      - installer
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:9428 || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - app-network

  frontend:
    user: root
    build:
      context: ./frontend
      args:
        - API_URL=http://backend:9428
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/dist
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "4200:4200"
    restart: unless-stopped
    depends_on:
      - backend
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:4200 || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - app-network

networks:
  app-network:
    driver: bridge